### ISSUE TITLE
Update multibuild to a version that strips binaries in wheels

### ISSUE THREAD

**Issue by xhochy** [MacPython/matplotlib-wheels#4]
On the next release, please update the multibuild submodule to matthew-brett/multibuild@b2748e5 or newer. This should reduce the size of the Matplotlib wheels from 14,3M to 12M by excluding unnecessary debug symbols. The more important change is that the extracted files on disk are significantly smaller, e.g. when you install matplotlib in a docker container, then the size reduction is very noticable.

**Comment by tacaswell** [comment]
attn @matthew-brett   I am not comfortable enough with either git sub-modules or how this system works to do this.
